### ISSUE TITLE
Remote commands doesn't work

### ISSUE THREAD

**Issue by ProfessorBrain** [galaxy119/DiscordIntegration#12]
Look at this: https://discord.com/channels/656673194693885975/656709515936530445/736922849335312444 in discord

**Comment by galaxy119** [comment]
When using plugin commands directly in the console, you must preceed the command with a ``/``

IE: 
``list``
becomes
``/list``


The bot itself doesn't currently support more than a single character for it's bot prefix, which is why it's not able to relay the correct commands to the server.
