### ISSUE TITLE
Missing arguments in the Command Log Channel.

### ISSUE THREAD

**Issue by 1vs9-standart** [galaxy119/DiscordIntegration#14]
The screenshot shows a clear lack of arguments. It is not possible to understand what exactly was issued, etc.
https://cdn.discordapp.com/attachments/610811426193539084/738091073477410996/unknown.png

**Comment by DGvagabond** [comment]
This has been fixed internally and should no longer be an issue in the next release!

**Comment by galaxy119** [comment]
Fixed in c32e551d49fdf8303e2a3a54ecac15f6af0ff550
