### ISSUE TITLE
Discord bot not writing logs

### ISSUE THREAD

**Issue by Feftheboss** [galaxy119/DiscordIntegration#22]
https://cdn.discordapp.com/attachments/757299913121071155/757689686436216962/637363014332598591.txt
There are all kinds of perms in bot but can't find the room in a way, I don't understand.
![unknown (7)](https://user-images.githubusercontent.com/71670181/93908628-8cf9c900-fd07-11ea-864b-84465475f21d.png)

**Comment by Feftheboss** [comment]
![image](https://user-images.githubusercontent.com/71670181/93910374-aef44b00-fd09-11ea-859a-72cbfee3c626.png)

**Comment by galaxy119** [comment]
"recievedDat Channel not found"

You didn't set the channelID for the log channels properly, or, you have the bot in multiple discord servers, which is not supported.

**Comment by Feftheboss** [comment]
''you have the bot in multiple discord servers'' that fixes my problem thanks.
