### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by TypicalIllusion** [galaxy119/DiscordIntegration#24]
When I run the bot everything is fine but when I run commands that are higher then permission 0,  I get permission denied. I have the role and the role id is set up properly. Windows 10 64 bit (if this matters)

**Comment by galaxy119** [comment]
Could you show me what your bot's config file looks like?

Is the command a plugin based one?
If so, are you sure it's the bot denying the command and not the plugin?

**Comment by TypicalIllusion** [comment]
the command is any command with the permission value of 1-4.
{"Debug":false,"BotPrefix":"+","BotToken":"my token","Port":7777,"PermLevel1Id":768146312796569641,"Permlevel2Id":768146312796569641,"Permlevel3Id":768146312796569641,"Permlevel4Id":768146312796569641,"CommandLogChannelId":0,"GameLogChannelId":0,"AllowedCommands":{"list":0,"bc":4,"kick":4,"ban":4},"EggMode":false}

**Comment by TypicalIllusion** [comment]
its like it doesnt notice the role or anything

**Comment by TypicalIllusion** [comment]
[same thing but in notepad.txt](https://github.com/galaxy119/DiscordIntegration/files/5413040/same.thing.but.in.notepad.txt)
this aswell

**Comment by TypicalIllusion** [comment]
im still getting the "perm denied". i changed the role but that didnt work

**Comment by galaxy119** [comment]
It's because you have the roleID in all 4 perm levels, but it only registers the role ID for the first one that it appears in. Take it out of perm level 1 2 and 3, and it will work.

**Comment by TypicalIllusion** [comment]
oh alright

**Comment by TypicalIllusion** [comment]
another thing is, if i have perm 4 id and i have a command the requires perm 3 id, can i use perm 3 if i have the perm 4 role? or do i need to add the permission 3 role aswell

**Comment by galaxy119** [comment]
https://github.com/galaxy119/DiscordIntegration/blob/master/README.md

![image](https://user-images.githubusercontent.com/10914157/96862308-2658ef80-141a-11eb-9e11-e1f9e7e3ce8c.png)

**Comment by TypicalIllusion** [comment]
alright, thanks for all the help. the bot is working
