### ISSUE TITLE
Config keeps resetting to default config settings for unkown reason.

### ISSUE THREAD

**Issue by Oyplap** [galaxy119/DiscordIntegration#27]
Hello,
I don't know why but the DiscordIntegration config in (for example) 7777-config.yml keeps resetting. I don't know what triggers it but this happens for quite some time.

**Comment by galaxy119** [comment]
Likely because you're fucking it up.

**Comment by Oyplap** [comment]
Yeah sorry, I forgot to close this because I did fuck things up.
